//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("x3v6Model1", "FK_PackingDetail_Packing", "Packing", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PackingClassLibrary.Packing), "PackingDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PackingClassLibrary.PackingDetail), true)]

#endregion

namespace PackingClassLibrary
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class local_x3v6Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new local_x3v6Entities object using the connection string found in the 'local_x3v6Entities' section of the application configuration file.
        /// </summary>
        public local_x3v6Entities() : base("name=local_x3v6Entities", "local_x3v6Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new local_x3v6Entities object.
        /// </summary>
        public local_x3v6Entities(string connectionString) : base(connectionString, "local_x3v6Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new local_x3v6Entities object.
        /// </summary>
        public local_x3v6Entities(EntityConnection connection) : base(connection, "local_x3v6Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Packing> Packings
        {
            get
            {
                if ((_Packings == null))
                {
                    _Packings = base.CreateObjectSet<Packing>("Packings");
                }
                return _Packings;
            }
        }
        private ObjectSet<Packing> _Packings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PackingDetail> PackingDetails
        {
            get
            {
                if ((_PackingDetails == null))
                {
                    _PackingDetails = base.CreateObjectSet<PackingDetail>("PackingDetails");
                }
                return _PackingDetails;
            }
        }
        private ObjectSet<PackingDetail> _PackingDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserMaster> UserMasters
        {
            get
            {
                if ((_UserMasters == null))
                {
                    _UserMasters = base.CreateObjectSet<UserMaster>("UserMasters");
                }
                return _UserMasters;
            }
        }
        private ObjectSet<UserMaster> _UserMasters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SKU_URL_Info> SKU_URL_Info
        {
            get
            {
                if ((_SKU_URL_Info == null))
                {
                    _SKU_URL_Info = base.CreateObjectSet<SKU_URL_Info>("SKU_URL_Info");
                }
                return _SKU_URL_Info;
            }
        }
        private ObjectSet<SKU_URL_Info> _SKU_URL_Info;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Packings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPackings(Packing packing)
        {
            base.AddObject("Packings", packing);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PackingDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPackingDetails(PackingDetail packingDetail)
        {
            base.AddObject("PackingDetails", packingDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserMasters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserMasters(UserMaster userMaster)
        {
            base.AddObject("UserMasters", userMaster);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SKU_URL_Info EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSKU_URL_Info(SKU_URL_Info sKU_URL_Info)
        {
            base.AddObject("SKU_URL_Info", sKU_URL_Info);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="x3v6Model1", Name="Packing")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Packing : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Packing object.
        /// </summary>
        /// <param name="packingId">Initial value of the PackingId property.</param>
        public static Packing CreatePacking(global::System.String packingId)
        {
            Packing packing = new Packing();
            packing.PackingId = packingId;
            return packing;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PackingId
        {
            get
            {
                return _PackingId;
            }
            set
            {
                if (_PackingId != value)
                {
                    OnPackingIdChanging(value);
                    ReportPropertyChanging("PackingId");
                    _PackingId = StructuralObject.SetValidValue(value, false, "PackingId");
                    ReportPropertyChanged("PackingId");
                    OnPackingIdChanged();
                }
            }
        }
        private global::System.String _PackingId;
        partial void OnPackingIdChanging(global::System.String value);
        partial void OnPackingIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BoxType
        {
            get
            {
                return _BoxType;
            }
            set
            {
                OnBoxTypeChanging(value);
                ReportPropertyChanging("BoxType");
                _BoxType = StructuralObject.SetValidValue(value, true, "BoxType");
                ReportPropertyChanged("BoxType");
                OnBoxTypeChanged();
            }
        }
        private global::System.String _BoxType;
        partial void OnBoxTypeChanging(global::System.String value);
        partial void OnBoxTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> BoxWeight
        {
            get
            {
                return _BoxWeight;
            }
            set
            {
                OnBoxWeightChanging(value);
                ReportPropertyChanging("BoxWeight");
                _BoxWeight = StructuralObject.SetValidValue(value, "BoxWeight");
                ReportPropertyChanged("BoxWeight");
                OnBoxWeightChanged();
            }
        }
        private Nullable<global::System.Double> _BoxWeight;
        partial void OnBoxWeightChanging(Nullable<global::System.Double> value);
        partial void OnBoxWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BoxDimension
        {
            get
            {
                return _BoxDimension;
            }
            set
            {
                OnBoxDimensionChanging(value);
                ReportPropertyChanging("BoxDimension");
                _BoxDimension = StructuralObject.SetValidValue(value, true, "BoxDimension");
                ReportPropertyChanged("BoxDimension");
                OnBoxDimensionChanged();
            }
        }
        private global::System.String _BoxDimension;
        partial void OnBoxDimensionChanging(global::System.String value);
        partial void OnBoxDimensionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value, "StartTime");
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartTime;
        partial void OnStartTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value, "EndTime");
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndTime;
        partial void OnEndTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEndTimeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("x3v6Model1", "FK_PackingDetail_Packing", "PackingDetail")]
        public EntityCollection<PackingDetail> PackingDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PackingDetail>("x3v6Model1.FK_PackingDetail_Packing", "PackingDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PackingDetail>("x3v6Model1.FK_PackingDetail_Packing", "PackingDetail", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="x3v6Model1", Name="PackingDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PackingDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PackingDetail object.
        /// </summary>
        /// <param name="packingDetailID">Initial value of the PackingDetailID property.</param>
        /// <param name="packingId">Initial value of the PackingId property.</param>
        public static PackingDetail CreatePackingDetail(global::System.Int64 packingDetailID, global::System.String packingId)
        {
            PackingDetail packingDetail = new PackingDetail();
            packingDetail.PackingDetailID = packingDetailID;
            packingDetail.PackingId = packingId;
            return packingDetail;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PackingDetailID
        {
            get
            {
                return _PackingDetailID;
            }
            set
            {
                if (_PackingDetailID != value)
                {
                    OnPackingDetailIDChanging(value);
                    ReportPropertyChanging("PackingDetailID");
                    _PackingDetailID = StructuralObject.SetValidValue(value, "PackingDetailID");
                    ReportPropertyChanged("PackingDetailID");
                    OnPackingDetailIDChanged();
                }
            }
        }
        private global::System.Int64 _PackingDetailID;
        partial void OnPackingDetailIDChanging(global::System.Int64 value);
        partial void OnPackingDetailIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PackingId
        {
            get
            {
                return _PackingId;
            }
            set
            {
                OnPackingIdChanging(value);
                ReportPropertyChanging("PackingId");
                _PackingId = StructuralObject.SetValidValue(value, false, "PackingId");
                ReportPropertyChanged("PackingId");
                OnPackingIdChanged();
            }
        }
        private global::System.String _PackingId;
        partial void OnPackingIdChanging(global::System.String value);
        partial void OnPackingIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SKUNumber
        {
            get
            {
                return _SKUNumber;
            }
            set
            {
                OnSKUNumberChanging(value);
                ReportPropertyChanging("SKUNumber");
                _SKUNumber = StructuralObject.SetValidValue(value, true, "SKUNumber");
                ReportPropertyChanged("SKUNumber");
                OnSKUNumberChanged();
            }
        }
        private global::System.String _SKUNumber;
        partial void OnSKUNumberChanging(global::System.String value);
        partial void OnSKUNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SKUQuantity
        {
            get
            {
                return _SKUQuantity;
            }
            set
            {
                OnSKUQuantityChanging(value);
                ReportPropertyChanging("SKUQuantity");
                _SKUQuantity = StructuralObject.SetValidValue(value, "SKUQuantity");
                ReportPropertyChanged("SKUQuantity");
                OnSKUQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _SKUQuantity;
        partial void OnSKUQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnSKUQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PackingDetailStartDateTime
        {
            get
            {
                return _PackingDetailStartDateTime;
            }
            set
            {
                OnPackingDetailStartDateTimeChanging(value);
                ReportPropertyChanging("PackingDetailStartDateTime");
                _PackingDetailStartDateTime = StructuralObject.SetValidValue(value, "PackingDetailStartDateTime");
                ReportPropertyChanged("PackingDetailStartDateTime");
                OnPackingDetailStartDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _PackingDetailStartDateTime;
        partial void OnPackingDetailStartDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnPackingDetailStartDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PackingDetailEndDateTime
        {
            get
            {
                return _PackingDetailEndDateTime;
            }
            set
            {
                OnPackingDetailEndDateTimeChanging(value);
                ReportPropertyChanging("PackingDetailEndDateTime");
                _PackingDetailEndDateTime = StructuralObject.SetValidValue(value, "PackingDetailEndDateTime");
                ReportPropertyChanged("PackingDetailEndDateTime");
                OnPackingDetailEndDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _PackingDetailEndDateTime;
        partial void OnPackingDetailEndDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnPackingDetailEndDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BoxQuantity
        {
            get
            {
                return _BoxQuantity;
            }
            set
            {
                OnBoxQuantityChanging(value);
                ReportPropertyChanging("BoxQuantity");
                _BoxQuantity = StructuralObject.SetValidValue(value, "BoxQuantity");
                ReportPropertyChanged("BoxQuantity");
                OnBoxQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _BoxQuantity;
        partial void OnBoxQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnBoxQuantityChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("x3v6Model1", "FK_PackingDetail_Packing", "Packing")]
        public Packing Packing
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Packing>("x3v6Model1.FK_PackingDetail_Packing", "Packing").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Packing>("x3v6Model1.FK_PackingDetail_Packing", "Packing").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Packing> PackingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Packing>("x3v6Model1.FK_PackingDetail_Packing", "Packing");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Packing>("x3v6Model1.FK_PackingDetail_Packing", "Packing", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="x3v6Model1", Name="SKU_URL_Info")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SKU_URL_Info : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SKU_URL_Info object.
        /// </summary>
        /// <param name="sKU">Initial value of the SKU property.</param>
        /// <param name="sKUrl">Initial value of the SKUrl property.</param>
        public static SKU_URL_Info CreateSKU_URL_Info(global::System.String sKU, global::System.String sKUrl)
        {
            SKU_URL_Info sKU_URL_Info = new SKU_URL_Info();
            sKU_URL_Info.SKU = sKU;
            sKU_URL_Info.SKUrl = sKUrl;
            return sKU_URL_Info;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SKU
        {
            get
            {
                return _SKU;
            }
            set
            {
                if (_SKU != value)
                {
                    OnSKUChanging(value);
                    ReportPropertyChanging("SKU");
                    _SKU = StructuralObject.SetValidValue(value, false, "SKU");
                    ReportPropertyChanged("SKU");
                    OnSKUChanged();
                }
            }
        }
        private global::System.String _SKU;
        partial void OnSKUChanging(global::System.String value);
        partial void OnSKUChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SKUrl
        {
            get
            {
                return _SKUrl;
            }
            set
            {
                if (_SKUrl != value)
                {
                    OnSKUrlChanging(value);
                    ReportPropertyChanging("SKUrl");
                    _SKUrl = StructuralObject.SetValidValue(value, false, "SKUrl");
                    ReportPropertyChanged("SKUrl");
                    OnSKUrlChanged();
                }
            }
        }
        private global::System.String _SKUrl;
        partial void OnSKUrlChanging(global::System.String value);
        partial void OnSKUrlChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="x3v6Model1", Name="UserMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserMaster object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        public static UserMaster CreateUserMaster(global::System.Int64 userID)
        {
            UserMaster userMaster = new UserMaster();
            userMaster.UserID = userID;
            return userMaster;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value, "UserID");
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int64 _UserID;
        partial void OnUserIDChanging(global::System.Int64 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true, "UserName");
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserAddress
        {
            get
            {
                return _UserAddress;
            }
            set
            {
                OnUserAddressChanging(value);
                ReportPropertyChanging("UserAddress");
                _UserAddress = StructuralObject.SetValidValue(value, true, "UserAddress");
                ReportPropertyChanged("UserAddress");
                OnUserAddressChanged();
            }
        }
        private global::System.String _UserAddress;
        partial void OnUserAddressChanging(global::System.String value);
        partial void OnUserAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UserJoiningDate
        {
            get
            {
                return _UserJoiningDate;
            }
            set
            {
                OnUserJoiningDateChanging(value);
                ReportPropertyChanging("UserJoiningDate");
                _UserJoiningDate = StructuralObject.SetValidValue(value, "UserJoiningDate");
                ReportPropertyChanged("UserJoiningDate");
                OnUserJoiningDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UserJoiningDate;
        partial void OnUserJoiningDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUserJoiningDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserAccessChar
        {
            get
            {
                return _UserAccessChar;
            }
            set
            {
                OnUserAccessCharChanging(value);
                ReportPropertyChanging("UserAccessChar");
                _UserAccessChar = StructuralObject.SetValidValue(value, true, "UserAccessChar");
                ReportPropertyChanged("UserAccessChar");
                OnUserAccessCharChanged();
            }
        }
        private global::System.String _UserAccessChar;
        partial void OnUserAccessCharChanging(global::System.String value);
        partial void OnUserAccessCharChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserPassword
        {
            get
            {
                return _UserPassword;
            }
            set
            {
                OnUserPasswordChanging(value);
                ReportPropertyChanging("UserPassword");
                _UserPassword = StructuralObject.SetValidValue(value, true, "UserPassword");
                ReportPropertyChanged("UserPassword");
                OnUserPasswordChanged();
            }
        }
        private global::System.String _UserPassword;
        partial void OnUserPasswordChanging(global::System.String value);
        partial void OnUserPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserFullName
        {
            get
            {
                return _UserFullName;
            }
            set
            {
                OnUserFullNameChanging(value);
                ReportPropertyChanging("UserFullName");
                _UserFullName = StructuralObject.SetValidValue(value, true, "UserFullName");
                ReportPropertyChanged("UserFullName");
                OnUserFullNameChanged();
            }
        }
        private global::System.String _UserFullName;
        partial void OnUserFullNameChanging(global::System.String value);
        partial void OnUserFullNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserStation
        {
            get
            {
                return _UserStation;
            }
            set
            {
                OnUserStationChanging(value);
                ReportPropertyChanging("UserStation");
                _UserStation = StructuralObject.SetValidValue(value, true, "UserStation");
                ReportPropertyChanged("UserStation");
                OnUserStationChanged();
            }
        }
        private global::System.String _UserStation;
        partial void OnUserStationChanging(global::System.String value);
        partial void OnUserStationChanged();

        #endregion

    }

    #endregion

}
